# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

# ✅ Enable both modular headers & frameworks
use_frameworks! :linkage => :static
use_modular_headers!

prepare_react_native_project!

target 'runit_fe' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # ✅ Ensure ReactCommon is linked properly
  pod 'ReactCommon', :path => '../node_modules/react-native/ReactCommon'

  post_install do |installer|
    # ✅ This post_install hook is needed for React Native
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
